title: Raspberry Pi Foundation Project Creation Process
hero_image: images/banner.png
description: default-project-template description
version: 1
listed: false
copyedit: false
last_tested: "2025-01-01"
steps:
  - title: Getting started
  - title: Creating a new project
  - title: Troubleshooting
  - title: What happens next?
  - title: Start writing your project
  - title: Basic markdown tips

